name: Build Pico Launcher release

on:
  release:
    types: [published]

jobs:
  pico_launcher:
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-v1.16.0
    name: Build Pico Launcher
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install zip
        run:
          apt-get update && apt-get -y install zip
      - name: Run build script
        run: |
          make
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4
        with:
          path: |
            _pico/
            LAUNCHER.nds
          name: Pico_Launcher
      - name: Package for release
        run: |
          mkdir Pico_Launcher
          cp -r _pico/ LAUNCHER.nds Pico_Launcher
          cd Pico_Launcher && zip -r $PWD.zip *
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Pico_Launcher.zip
